### PR TITLE
Markup - Added custom filters and functions

### PR DESCRIPTION
**Pull request by WebVPF**
Documentation page https://wintercms.com/docs/v1.2/markup/templating/templating

Link to the page https://wintercms.com/docs/v1.2/docs/plugin/registration#extending-twig

### CODE REVIEW

**Comment by mjauvin** [comment]
This already exists under the `Plugin Registration section`.

**Comment by WebVPF** [comment]
> This already exists under the `Plugin Registration section`.

@mjauvin Where? Can you show the link?

**Comment by mjauvin** [comment]
https://wintercms.com/docs/v1.2/docs/plugin/registration#supported-methods
https://wintercms.com/docs/v1.2/docs/plugin/registration#extending-twig

**Comment by WebVPF** [comment]
@mjauvin Did you see what I added to the pull request? And where did I add.

**Comment by mjauvin** [comment]
> @mjauvin Did you see what I added to the pull request? And where did I add.

Yes.
I guess it doesn't hurt to add this in there.

**Comment by WebVPF** [comment]
@mjauvin thanks for sorting it out

---

I know that you can add your own Twig filters and functions. I've used this more than once. But I don’t remember where and how they need to be defined. So I open the documentation.
I don't remember where in the documentation it is stated about this. So I start looking. Having searched and not found, I go to the Markup section, it is logical that there should be some mention of this in this section.
Finding nothing, I return back to the Winter documentation. I find the right method, but not right away.
It turns out I'm wasting a lot of time.

This has happened to me several times already. So I added a link to the Markup documentation. It should be there to make it easier to find.

**Comment by WebVPF** [comment]
@LukeTowers accept this PR

**Pull request merged**
