### PR TITLE
Document enhanced protected state

### PR DESCRIPTION
**Pull request by arvislacis**
All credits to @LukeTowers as this is his (https://github.com/wintercms/docs/pull/148/commits/f88cf3764a429abadfab551501c223a6d792f070) commit but just created as another PR to don't inference with https://github.com/wintercms/docs/pull/148 - probably should not have commited to this PR but to the `develop` branch instead .

### CODE REVIEW

**Comment by LukeTowers** [comment]
I committed it to the 1.2 branch directly instead of develop. @bennothommo are the docs github URLs setup to pull from / point to develop or the 1.2 branch?

**Comment by bennothommo** [comment]
@LukeTowers should be the 1.2 branch.

**Comment by LukeTowers** [comment]
@bennothommo my personal preference would be to make it point to the develop branch and then only merge the develop branch into the 1.2 branch when we do the same with the main repo, but make the main docs always load from the develop branch. Any thoughts?

**Comment by bennothommo** [comment]
@LukeTowers I'd be happy to do that if we actually make it clear that it's the "develop" branch on the docs. I feel that stating it as the `v1.2` docs might mislead people who stick to the stable releases and try to use a bleeding edge feature that hasn't yet been released.

**Comment by LukeTowers** [comment]
@bennothommo how hard would it be to add the version selector like Laravel has?

**Comment by bennothommo** [comment]
Shouldn't be too difficult - I think I had already somewhat made some moves towards that with Nabu.

Effectively, we'd just need to copy the 4 sets of documentation in the `winterdocs` plugin and add them again, pointing each of them to `develop` (or another version's branch).

I think I had set up the version picker at the top to look at specific version numbers and group the Main Docs, Markup, UI and API under each "version" group we had set up.

**Comment by LukeTowers** [comment]
@bennothommo are you willing to implement that or do you need me to take a stab at it? We'll need to adjust the redirects as well.

**Comment by bennothommo** [comment]
Yeah I'll just finalise this work for Snowboard, and then I'll add it in.

**Pull request closed without merging**
