### PR TITLE
Add frontend events timeline page

### PR DESCRIPTION
**Pull request by mjauvin**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Could we add links to each of these? Also it could be useful to add example code that could be added that will show every event that has been fired in a given request in the order that it was fired.

**Comment by mjauvin** [comment]
> Also it could be useful to add example code that could be added that will show every event that has been fired in a given request in the order that it was fired.

What do you mean exactly @LukeTowers

**Comment by LukeTowers** [comment]
You can add a wildcard listener that can be auto-attached to every event in the request and then collect the names of those events before outputting the results at the end of the request.

**Comment by mjauvin** [comment]
> You can add a wildcard listener that can be auto-attached to every event in the request and then collect the names of those events before outputting the results at the end of the request.

@LukeTowers Although I agree this would be useful, I don't think this should prevent the current PR to be merged. This could be added later on as a seperate PR.

**Comment by bennothommo** [comment]
I do think we need to at least have a description of the event and its intention, otherwise, this page is going to be very light.

**Comment by mjauvin** [comment]
@LukeTowers I added an example code snippet to dump the events history.

**Comment by mjauvin** [comment]
Can this be merged?

**Pull request merged**
