### PR TITLE
md_line Twig filter

### PR DESCRIPTION
**Pull request by matteotrubini**
See wintercms/winter#370 - to be merged on v1.1.8 release

### CODE REVIEW

**Comment by LukeTowers** [comment]
Just include this one and the md_safe ones on the `| md` filter page instead of creating a new page for it please. Side note, if new pages are created they need to be added to the table of contents in the config folder as well.

**Comment by matteotrubini** [comment]
Done.

PS: maybe makes sense also to add `| md_clean` to expose `Markdown::parseClean()` ? See wintercms/storm@2d8fb579834c6b79f115c792116fc4e5be6604e1

**Comment by LukeTowers** [comment]
Sounds good to me

**Comment by LukeTowers** [comment]
Had to merge in https://github.com/wintercms/docs/commit/f99a0ab80090413f5eedb09705108417ae453f1d, force pushing breaks our merge flow @matteotrubini. Thanks for the contribution!

**Pull request closed without merging**
