### PR TITLE
Markup - Added url function

### PR DESCRIPTION
**Pull request by WebVPF**

### CODE REVIEW

**Comment by WebVPF** [comment]
New changes:
- [Markup - Added url function](https://github.com/wintercms/docs/pull/185/commits/74605ae71e00739b4bf4264cdf7b6011c80db197)
- [Added menu item](https://github.com/wintercms/docs/pull/185/commits/f7d8156dac5a9265c212ef99041df4950fcf87cd)

The rest was pulled from the **develop** branch.


With the new functionality there is only this:
- [Add documentation for new mix options](https://github.com/wintercms/docs/pull/185/commits/6e2e294e3c3238baf121a72b937d24b7b87fcebb)

Leave it or close it and make a new PR?

**Comment by LukeTowers** [comment]
Thanks @WebVPF! I've just switched the base branch to develop, we can merge from develop into 1.2 a bit later.

**Comment by WebVPF** [comment]
@LukeTowers Can you merge branches and update the documentation on the site?

**Comment by WebVPF** [comment]
@LukeTowers Can you merge branches and update the documentation on the site?

**Comment by LukeTowers** [comment]
@WebVPF yes, I need to change it to building the docs using queued jobs, it times out on vapor trying to do it all at once.

**Pull request merged**
