### PR TITLE
Document HasRelationships trait methods

### PR DESCRIPTION
**Pull request by mjauvin**
Related: https://github.com/wintercms/storm/pull/46 (specifically: https://github.com/wintercms/storm/commit/b977610d361cc25f24b05062e40a83a6d53680a8)
Mention the new addRelation() methods in the model extension docs.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin could you add some more headings and links to the ToC to more easily find these sections on the page?

**Comment by mjauvin** [comment]
Done @LukeTowers

**Comment by LukeTowers** [comment]
@mjauvin I meant also add the anchor tags and the headings to the page's ToC at the top

**Comment by mjauvin** [comment]
@LukeTowers from what I can tell, the new format adds this automatically, unless I am mistaken @bennothommo ?

**Comment by mjauvin** [comment]
Guys, anything preventing this to be merged?

**Comment by bennothommo** [comment]
@mjauvin if you could add type hints to those methods - ie. `(string $name, array $config)` - I'm happy for you to merge.

**Pull request merged**
