### PR TITLE
Fix links in markup docs

### PR DESCRIPTION
**Pull request by WebVPF**
https://wintercms.com/docs/v1.2/markup

### CODE REVIEW

**Review by LukeTowers — APPROVED** [review]

**Comment by arvislacis** [comment]
Should be merged also in 1.2 branch for changes to be reflected on Docs website.

**Comment by LukeTowers** [comment]
Changes are reflected in the docs website when we clear the cache; we need to add that as a step to the webhook processing.

**Comment by WebVPF** [comment]
@LukeTowers please clear the cache

**Comment by LukeTowers** [comment]
Done @WebVPF

**Comment by WebVPF** [comment]
@LukeTowers
Fixes from this pull request did not apply.
Here is the first link https://wintercms.com/docs/v1.2/markup/this/page
Should be like this: `../../docs/cms/pages#page-variables`

It turns out that the pull request was made in the wrong branch.

**Comment by LukeTowers** [comment]
@WebVPF thanks, I merged it into the correct branch but the site is waiting on a PR to allow for both branches to play nicely together. At the moment I'm just having trouble with the UI for switching between branches of the documentation, perhaps you could have a look and let me know your thoughts?

image

image

I don't like how duplicated it looks and feel like there's a better way to handle selecting from a different version of the docs, but don't have time to mock up an example at the moment. Do you think you could take a stab at it or provide some input?

**Comment by LukeTowers** [comment]
Ideally the release flow will be that the main docs on the website will be the dev branch (so the master branch like on Laravel) and then if people want to switch to a different version they can; with the docs release cycle following the same as the main code itself (when a new version is released dev is merged into the current main branch for the main winter repo as well as now the docs repo).

**Comment by LukeTowers** [comment]
Note that I'd like to be able to provide each of the main branches (currently 1.1, 1.2, and dev, but very soon 1.3, 1.4, etc)

**Comment by WebVPF** [comment]
@LukeTowers 
Version selection through the select element:

**Comment by LukeTowers** [comment]
@bennothommo does that work for you?

**Comment by bennothommo** [comment]
@LukeTowers @WebVPF I suppose that will work, but will need to find a new home for the theme switcher (dark/light).

To be honest, I also want to remove the landing page altogether - it's an unnecessary extra click to get to where you want. It's only in the Nabu theme as an example.

**Comment by WebVPF** [comment]
@bennothommo

**Comment by bennothommo** [comment]
@WebVPF I went this way, implementing your ideas:

**Comment by WebVPF** [comment]
@LukeTowers Will the fixes from this Pull Request ever work in the documentation on the site?

**Comment by LukeTowers** [comment]
@WebVPF yes, we have pending changes to the main website docs, just waiting for us to finish testing / merge it in. Check back in with me in a week if I haven't dealt with it by then.

**Comment by WebVPF** [comment]
@LukeTowers will this PR be included in the documentation?

**Comment by LukeTowers** [comment]
@bennothommo I can't remember at the moment, was there anything special we needed to do to trigger the docs to update on the main website? I know we still have to merge the multi-branch support PR but this should have been deployed automatically when I merged the 1.2.4 docs pr into the 1.2 branch AFAIK.

**Comment by bennothommo** [comment]
@LukeTowers I think we have them hooked up to webhooks, but there is a URL you can go to direct to refresh the docs. I can send to you if needed :)

**Comment by LukeTowers** [comment]
@bennothommo please do :)

**Pull request merged**
