### PR TITLE
Added extension parameter to ImageResizer

### PR DESCRIPTION
**Pull request by WebVPF**
Documentation page: https://wintercms.com/docs/v1.2/docs/services/image-resizing#available-parameters

### CODE REVIEW

**Comment by WebVPF** [comment]
I have a question:
does ImageResizer support custom image name?

Ex.:
```twig
{{ item.logo.thumb(200, 150, { 'imagename': 'logo-' ~ item.slug, 'extension': 'webp' }) }}
```
Result:
`old-name.jpg` -> `logo-slug.webp`

**Comment by AIC-BV** [comment]
😱 Since when is this possible? I've been using JPGs for the last few years!

@LukeTowers Is it still good practice to use [TinyPNG](https://github.com/wintercms/wn-tinypng-plugin) to make the images smaller first? Or is webp so small that this isn't needed anymore?

**Comment by AIC-BV** [comment]
I assume a fallback to JPG is no longer needed? https://caniuse.com/webp

**Comment by AIC-BV** [comment]
This enhancement is no longer needed for me because of the new resize parameter
https://github.com/wintercms/wn-tinypng-plugin/issues/2

**Comment by WebVPF** [comment]
> 😱 Since when is this possible? I've been using JPGs for the last few years!

This was available even before the fork.

Example:
```twig
<img src="{{ user.avatar.getThumb(90, 90, {'mode': 'exact', 'quality': 80, 'extension': 'webp'}) }}" width="90" height="90" alt="{{ user.name }}" />
```
or
```twig
<img src="{{ item.foto.thumb(400, 300, {'extension': 'webp'}) }}" />
```

**Comment by damsfx** [comment]
> 😱 Since when is this possible? I've been using JPGs for the last few years!
> 

One more for me!  
I was completely unaware of this parameter.

Is this option related to other platform requirements?

**Comment by WebVPF** [comment]
> Is this option related to other platform requirements?

The only requirement is that the source image file must have the extension `jpg`, `jpeg`, `png`, `gif`, `webp`.
https://github.com/wintercms/storm/blob/dd89dc140bfdb0e209437b2263b711b8fa655981/src/Database/Attach/File.php#L65

---
All parameters: https://github.com/wintercms/storm/blob/dd89dc140bfdb0e209437b2263b711b8fa655981/src/Database/Attach/File.php#L622-L629

Default values: https://github.com/wintercms/storm/blob/dd89dc140bfdb0e209437b2263b711b8fa655981/src/Database/Attach/File.php#L689-694

---

There is one more parameter that is not specified in the documentation. This is `interlace`.

`interlace`: Interlace image,  Boolean: `false` (disabled: default), `true` (enabled)
https://github.com/wintercms/storm/blob/dd89dc140bfdb0e209437b2263b711b8fa655981/src/Database/Attach/Resizer.php#L156-L176

In my opinion, this is something outdated for today's Internet.

---

I don't see in the code whether there is a parameter to set an SEO-friendly name for the file. Lighthouse doesn't like the generated file names.

**Comment by damsfx** [comment]
> The only requirement is that the source image file must have the extension `jpg`, `jpeg`, `png`, `gif`, `webp`. https://github.com/wintercms/storm/blob/dd89dc140bfdb0e209437b2263b711b8fa655981/src/Database/Attach/File.php#L65

I'd never realized before that this amazing feature was available!

> There is one more parameter that is not specified in the documentation. This is `interlace`.
> ... 
> In my opinion, this is something outdated for today's Internet.

Totally agree.
 
> I don't see in the code whether there is a parameter to set an SEO-friendly name for the file. Lighthouse doesn't like the generated file names.

Yes, this is a serious concern for good image SEO.

**Comment by LukeTowers** [comment]
The ImageResizer's image URLs for all file types except for FileAttachements should be SEO friendly, is it not?

**Pull request merged**
