### PR TITLE
Added Snowboard framework to asset compilation doc

### PR DESCRIPTION
**Pull request by WebVPF**

### CODE REVIEW

**Review by LukeTowers — APPROVED** [review]

**Comment by mjauvin** [comment]
@LukeTowers I thought we established this couldn't be used since the asset is already webpacked?

**Comment by WebVPF** [comment]
Nobody deleted this in the Snowboard documentation:
https://wintercms.com/docs/snowboard/introduction#framework-script-manual

**Comment by LukeTowers** [comment]
Good point @mjauvin, @WebVPF could you remove both sections?

**Comment by WebVPF** [comment]
@LukeTowers Done

**Comment by bennothommo** [comment]
@LukeTowers @mjauvin can you still use the aliases without passing it through the combiner?

**Comment by LukeTowers** [comment]
@bennothommo I think that the combiner aliases are only used when the input is processed by the combiner, not sure how'd you'd use one without the other.

**Comment by bennothommo** [comment]
I figured that maybe the syntax `@snowboard.base | theme` would work, since only arrays are passed through the combiner. But you're probably right - I might instead switch up the docs to show a custom build with the Mix commands instead.

**Comment by WebVPF** [comment]
@LukeTowers  Snowboard aliases are currently registered: https://github.com/wintercms/winter/blob/develop/modules/system/classes/CombineAssets.php#L165-L172

**Comment by bennothommo** [comment]
@WebVPF the aliases are registered, but the problem is because Snowboard is already minified, they're causing issues when they're put through the Asset Combiner, which minifies them a second time. The aliases are only used when put through the Asset Combiner in this fashion.

**Pull request merged**
