### PR TITLE
Added link to image resizing options

### PR DESCRIPTION
**Pull request by WebVPF**
Here in the table, `thumbOptions` parameter: https://wintercms.com/docs/v1.2/docs/backend/forms#file-upload

The link goes here: https://wintercms.com/docs/v1.2/docs/services/image-resizing#available-parameters

### CODE REVIEW

**Review by LukeTowers — APPROVED** [review]

**Comment by LukeTowers** [comment]
@mjauvin are you able to fix the linting errors or have they already been fixed on the develop branch?

**Comment by mjauvin** [comment]
@LukeTowers from what I can see in the code, they have been fixed in develop. Furthermore, my last PR to the docs(#159) passed without those warnings.

**Comment by mjauvin** [comment]
@WebVPF for future PRs to the docs, submit against the develop branch.

**Comment by WebVPF** [comment]
@mjauvin I proceeded to edit from the link on the documentation page

**Comment by damsfx** [comment]
@LukeTowers @mjauvin there's a strange behavior with the documentation site.  

The link above have an anchor to `file-upload` (https://wintercms.com/docs/v1.2/docs/backend/forms#file-upload), but I'm redirected to the `icon-picker` section (https://wintercms.com/docs/v1.2/docs/backend/forms#icon-picker).

Did one of you guys are in concern with it too ?

**Comment by mjauvin** [comment]
@WebVPF right, ok. @bennothommo is that what we want or should we link to the develop branch ?

**Comment by mjauvin** [comment]
> @LukeTowers @mjauvin there's a strange behavior with the documentation site.
> 
> The link above have an anchor to `file-upload` (https://wintercms.com/docs/v1.2/docs/backend/forms#file-upload), but I'm redirected to the `icon-picker` section (https://wintercms.com/docs/v1.2/docs/backend/forms#icon-picker).
> 
> Did one of you guys are in concern with it too ?

Yeah, I've been noticing this as well. There's some magic happening while scrolling (this updates the anchor in the browser URL) and I think this is creating problems when first accessing the full URL that includes the anchor.

@bennothommo any idea ?

**Comment by bennothommo** [comment]
> @WebVPF right, ok. @bennothommo is that what we want or should we link to the develop branch ?

@mjauvin the intention was for the docs versions to match the Winter versions, so if the docs are for a fix/feature in the `develop` branch, it should be added to the `develop` branch of the docs. If it's to fix up an issue with the docs for a fix/feature already present in Winter's `1.2` branch, then it should be made to the `1.2` branch of the docs too.

**Comment by bennothommo** [comment]
> Yeah, I've been noticing this as well. There's some magic happening while scrolling (this updates the anchor in the browser URL) and I think this is creating problems when first accessing the full URL that includes the anchor.
>
> @bennothommo any idea ?

Yeah, I'm aware of that issue. I'll try and fix it today.

**Comment by LukeTowers** [comment]
@bennothommo were you able to fix the issue?

**Comment by bennothommo** [comment]
@LukeTowers I have fixed the issue locally, but it relies on the PR to Winter to use the external Snowboard library, as the Nabu theme uses a custom app/Snowboard build.

**Comment by LukeTowers** [comment]
Can you ping me in whatever PRs need review for that again @bennothommo?

**Comment by bennothommo** [comment]
@LukeTowers this one is the main one: https://github.com/wintercms/winter/pull/980

**Pull request merged**
