### PR TITLE
Update link in docs to Web based installation

### PR DESCRIPTION
**Pull request by ahangarha**

### CODE REVIEW

**Comment by bennothommo** [comment]
Thanks @ahangarha!

**Comment by LukeTowers** [comment]
@bennothommo why are we not calling this the Wizard installer anymore?

**Comment by bennothommo** [comment]
@LukeTowers I hadn't used the word "wizard" in the web installer, so I just wanted to make sure there was no confusion. I feel that "wizard" is a bit old-hat terminology in this day and age, but happy to change it back if you want?

**Comment by seanthepottingshed** [comment]
What about mage?

**Pull request merged**
