### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by nmiyazaki-chapleau**
Here's a resubmit of #190 but to the develop branch.

### CODE REVIEW

**Comment by mjauvin** [comment]
This is not right, services/helpers.md has unwanted changes.

**Comment by nmiyazaki-chapleau** [comment]
services/helpers.md was changed in commit 4a0bd8f7e47c16f44c9c3913f7e88096a29057ef on the branch 1.2 but wasn't committed to develop. I can still remove it from this PR if you prefer?

**Comment by mjauvin** [comment]
Nah, I think I remember @bennothommo merges everything back to develop if needed, so I'll close this pr. Sorry for the trouble.

**Comment by nmiyazaki-chapleau** [comment]
Gotcha, no worries!

**Pull request closed without merging**
